#docker run -ti --rm --net="host" -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix firefox_firefox
firefox:
  build: .
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
  environment:
    DISPLAY: $DISPLAY
